import { useEffect, useState } from 'react'
import { ArrowRightLeft, Clock3, Plus, RotateCcw, Search, X } from 'lucide-react'
import useAuth from '../../hooks/useAuth'

const read = (key) => { try { return JSON.parse(localStorage.getItem(key)) || [] } catch { return [] } }
const matches = (value, user) => [user?.fullName, user?.email, user?.employeeId].filter(Boolean).some((item) => value?.toLowerCase() === item.toLowerCase())

export default function ReturnRequests() {
  const { user } = useAuth(); const identity = user?.fullName || user?.email
  const allocations = read('assetflow_allocations').filter((item) => item.status === 'Active' && matches(item.holder, user))
  const employees = read('assetflow_employees').filter((item) => item.department === user?.department && item.status === 'Active' && !matches(item.name, user))
  const [returns, setReturns] = useState(() => read('assetflow_return_requests'))
  const [transfers, setTransfers] = useState(() => read('assetflow_transfers'))
  const [tab, setTab] = useState('return'); const [search, setSearch] = useState(''); const [form, setForm] = useState(null)
  useEffect(() => { localStorage.setItem('assetflow_return_requests', JSON.stringify(returns)) }, [returns])
  useEffect(() => { localStorage.setItem('assetflow_transfers', JSON.stringify(transfers)) }, [transfers])
  const myReturns = returns.filter((item) => matches(item.requestedBy, user) && [item.id, item.assetName, item.reason, item.status].some((value) => value.toLowerCase().includes(search.toLowerCase())))
  const myTransfers = transfers.filter((item) => matches(item.from, user) && [item.id, item.assetName, item.to, item.status].some((value) => value.toLowerCase().includes(search.toLowerCase())))
  const submit = (event) => { event.preventDefault(); const allocation = allocations.find((item) => item.assetTag === form.assetTag); if (tab === 'return') setReturns([{ id: `RR-${String(returns.length + 1).padStart(4, '0')}`, assetTag: allocation.assetTag, assetName: allocation.assetName, requestedBy: identity, department: allocation.department, reason: form.reason, preferredDate: form.preferredDate, status: 'Requested', requestedOn: new Date().toLocaleDateString('en-IN') }, ...returns]); else setTransfers([...transfers, { id: `TR-${String(100 + transfers.length).padStart(4, '0')}`, assetTag: allocation.assetTag, assetName: allocation.assetName, from: identity, to: form.to, department: allocation.department, reason: form.reason, requestedOn: new Date().toLocaleDateString('en-IN'), status: 'Requested' }]); setForm(null) }
  const open = () => setForm(tab === 'return' ? { assetTag: '', reason: '', preferredDate: '' } : { assetTag: '', to: '', reason: '' })
  return <div className="mx-auto max-w-[1400px] space-y-6"><div className="flex justify-between"><div><p className="text-sm font-medium text-[#7a6475]">Personal requests</p><h1 className="mt-1 text-2xl font-bold text-[#31232e]">Return & Transfer Requests</h1><p className="mt-2 text-sm text-slate-600">Initiate and track requests only for assets currently allocated to you.</p></div><button disabled={!allocations.length} className="inline-flex h-fit items-center gap-2 rounded-lg bg-[#4f3448] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-40" onClick={open}><Plus size={18}/>New {tab === 'return' ? 'Return' : 'Transfer'} Request</button></div><div className="grid grid-cols-4 gap-4">{[['My Assets', allocations.length, Clock3], ['Pending Returns', myReturns.filter((item) => item.status === 'Requested').length, RotateCcw], ['Pending Transfers', myTransfers.filter((item) => item.status === 'Requested').length, ArrowRightLeft], ['Completed Requests', [...myReturns, ...myTransfers].filter((item) => ['Approved', 'Completed', 'Rejected'].includes(item.status)).length, Clock3]].map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-[#e6dee4] bg-white p-5"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><Icon className="text-[#4f3448]"/></div></div>)}</div><div className="grid grid-cols-2 gap-2 rounded-xl border border-[#e6dee4] bg-white p-2"><button className={`rounded-lg p-3 text-sm font-semibold ${tab === 'return' ? 'bg-[#4f3448] text-white' : 'text-slate-600'}`} onClick={() => setTab('return')}>Return Requests</button><button className={`rounded-lg p-3 text-sm font-semibold ${tab === 'transfer' ? 'bg-[#4f3448] text-white' : 'text-slate-600'}`} onClick={() => setTab('transfer')}>Transfer Requests</button></div><section className="rounded-xl border border-[#e6dee4] bg-white"><div className="border-b p-5"><div className="relative max-w-lg"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="w-full rounded-lg border border-[#ddd3da] py-2.5 pl-10 pr-3" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search my requests..."/></div></div><RequestTable rows={tab === 'return' ? myReturns : myTransfers} type={tab}/></section>{form && <RequestModal type={tab} form={form} setForm={setForm} allocations={allocations} employees={employees} submit={submit}/>}</div>
}
function RequestTable({ rows, type }) { return <table className="w-full text-left text-sm"><thead><tr className="border-b bg-[#fcfafb] text-xs uppercase text-slate-500">{(type === 'return' ? ['Request', 'Asset', 'Reason', 'Preferred Date', 'Requested On', 'Status'] : ['Request', 'Asset', 'Transfer To', 'Reason', 'Requested On', 'Status']).map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-b"><td className="px-4 py-4 font-semibold text-[#4f3448]">{item.id}</td><td className="px-4 py-4">{item.assetName}<small>{item.assetTag}</small></td>{type === 'transfer' && <td className="px-4 py-4">{item.to}</td>}<td className="px-4 py-4">{item.reason}</td>{type === 'return' && <td className="px-4 py-4">{item.preferredDate}</td>}<td className="px-4 py-4">{item.requestedOn}</td><td className="px-4 py-4"><span className="rounded-full bg-[#f1eaf0] px-2.5 py-1 text-xs font-semibold text-[#4f3448]">{item.status}</span></td></tr>)}</tbody></table> }
function RequestModal({ type, form, setForm, allocations, employees, submit }) { const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); const input = 'mt-2 w-full rounded-lg border border-[#ddd3da] px-3 py-2.5'; return <div className="fixed inset-0 z-20 grid place-items-center bg-black/35 p-6"><form className="w-full max-w-xl rounded-xl bg-white p-6" onSubmit={submit}><div className="flex justify-between"><h2 className="text-xl font-semibold">New {type === 'return' ? 'Return' : 'Transfer'} Request</h2><button type="button" onClick={() => setForm(null)}><X size={19}/></button></div><div className="mt-5 space-y-4"><label className="block text-sm font-medium">My Allocated Asset<select required className={input} name="assetTag" value={form.assetTag} onChange={update}><option value="">Select asset</option>{allocations.map((item) => <option key={item.assetTag} value={item.assetTag}>{item.assetTag} · {item.assetName}</option>)}</select></label>{type === 'transfer' && <label className="block text-sm font-medium">Transfer To<select required className={input} name="to" value={form.to} onChange={update}><option value="">Select department employee</option>{employees.map((item) => <option key={item.id}>{item.name}</option>)}</select></label>}{type === 'return' && <label className="block text-sm font-medium">Preferred Return Date<input required min={new Date().toISOString().slice(0, 10)} className={input} name="preferredDate" type="date" value={form.preferredDate} onChange={update}/></label>}<label className="block text-sm font-medium">Reason<textarea required rows="4" className={input} name="reason" value={form.reason} onChange={update}/></label></div><div className="mt-6 flex justify-end gap-3"><button className="rounded-lg border px-4 py-2.5" type="button" onClick={() => setForm(null)}>Cancel</button><button className="rounded-lg bg-[#4f3448] px-4 py-2.5 text-white">Submit Request</button></div></form></div> }
