import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowRightLeft, Bell, CalendarCheck, Check, CheckCheck, ClipboardCheck, Clock3, PackageCheck, Search, ShieldAlert, UserCog, Wrench, XCircle } from 'lucide-react'
import useAuth from '../../hooks/useAuth'

const readStore = (key, fallback = []) => { try { return JSON.parse(localStorage.getItem(key)) || fallback } catch { return fallback } }
const nowLabel = () => new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit' })
const iconMap = { asset: PackageCheck, maintenance: Wrench, booking: CalendarCheck, transfer: ArrowRightLeft, overdue: Clock3, audit: ClipboardCheck, user: UserCog, alert: AlertTriangle }
const colorMap = { asset: 'bg-blue-50 text-blue-700', maintenance: 'bg-amber-50 text-amber-700', booking: 'bg-violet-50 text-violet-700', transfer: 'bg-cyan-50 text-cyan-700', overdue: 'bg-red-50 text-red-700', audit: 'bg-orange-50 text-orange-700', user: 'bg-[#f1eaf0] text-[#4f3448]', alert: 'bg-red-50 text-red-700' }

function buildFeed() {
  const allocations = readStore('assetflow_allocations')
  const transfers = readStore('assetflow_transfers')
  const returns = readStore('assetflow_returns')
  const maintenance = readStore('assetflow_maintenance_requests')
  const bookings = readStore('assetflow_bookings')
  const reminders = readStore('assetflow_booking_reminders')
  const overdue = readStore('assetflow_overdue_allocations')
  const audits = readStore('assetflow_audit_cycles')
  const registeredUsers = readStore('assetflow_registered_users')

  const notifications = []
  const logs = []
  const add = (item, log = item) => { notifications.push(item); logs.push(log) }

  allocations.forEach((item) => add({ id: `allocation-${item.id}-${item.holder}`, type: 'asset', title: 'Asset Assigned', message: `${item.assetName} (${item.assetTag}) is assigned to ${item.holder}.`, time: item.allocatedOn || nowLabel(), module: 'Allocations', actor: 'Asset Manager', priority: 'normal' }, { id: `log-allocation-${item.id}`, type: 'asset', action: `Allocated ${item.assetTag} to ${item.holder}`, actor: 'Asset Manager', time: item.allocatedOn || nowLabel(), module: 'Allocations', detail: item.department }))
  transfers.forEach((item) => add({ id: `transfer-${item.id}-${item.status}`, type: 'transfer', title: `Transfer ${item.status}`, message: `${item.assetName} transfer from ${item.from} to ${item.to} is ${item.status.toLowerCase()}.`, time: item.requestedOn || nowLabel(), module: 'Transfers', actor: item.status === 'Approved' ? 'Asset Manager' : item.from, priority: item.status === 'Approved' ? 'normal' : 'attention' }, { id: `log-transfer-${item.id}`, type: 'transfer', action: `${item.status} transfer ${item.id}: ${item.from} → ${item.to}`, actor: item.status === 'Approved' ? 'Asset Manager' : item.from, time: item.requestedOn || nowLabel(), module: 'Transfers', detail: item.reason }))
  returns.forEach((item) => add({ id: `return-${item.id}`, type: 'asset', title: 'Asset Return Completed', message: `${item.assetName} was returned by ${item.holder || item.returnedBy} in ${item.condition} condition.`, time: item.date || item.returnedOn || nowLabel(), module: 'Returns', actor: item.holder || item.returnedBy, priority: 'normal' }, { id: `log-return-${item.id}`, type: 'asset', action: `Returned ${item.assetTag} in ${item.condition} condition`, actor: item.holder || item.returnedBy, time: item.date || nowLabel(), module: 'Returns', detail: item.notes }))
  maintenance.forEach((item) => { const rejected = item.status === 'Rejected'; add({ id: `maintenance-${item.id}-${item.status}`, type: 'maintenance', title: `Maintenance ${item.status}`, message: `${item.id} for ${item.assetName} is ${item.status.toLowerCase()}${item.technician ? ` · Technician: ${item.technician}` : ''}.`, time: item.raisedOn || nowLabel(), module: 'Maintenance', actor: item.raisedBy, priority: rejected || ['Critical', 'High'].includes(item.priority) ? 'attention' : 'normal' }, { id: `log-maintenance-${item.id}-${item.status}`, type: 'maintenance', action: `${item.status} maintenance request ${item.id}`, actor: item.technician || 'Asset Manager', time: item.raisedOn || nowLabel(), module: 'Maintenance', detail: item.issue }) })
  bookings.forEach((item) => { const status = item.status || 'Upcoming'; add({ id: `booking-${item.id}-${status}`, type: 'booking', title: `Booking ${status === 'Cancelled' ? 'Cancelled' : 'Confirmed'}`, message: `${item.resource} is booked by ${item.bookedBy} on ${item.date}, ${item.start}–${item.end}.`, time: item.date || nowLabel(), module: 'Bookings', actor: item.bookedBy, priority: 'normal' }, { id: `log-booking-${item.id}`, type: 'booking', action: `${status} booking ${item.id} for ${item.resource}`, actor: item.bookedBy, time: item.date || nowLabel(), module: 'Bookings', detail: item.title }) })
  reminders.forEach((item) => notifications.push({ id: `reminder-${item.id}`, type: 'booking', title: 'Booking Reminder', message: item.message, time: item.date || nowLabel(), module: 'Bookings', actor: 'System', priority: 'attention' }))
  overdue.forEach((item) => add({ id: `overdue-${item.id}`, type: 'overdue', title: 'Overdue Return Alert', message: `${item.assetName} (${item.assetTag}) held by ${item.holder} was due on ${item.expectedReturn}.`, time: item.expectedReturn, module: 'Allocations', actor: 'System', priority: 'critical' }, { id: `log-overdue-${item.id}`, type: 'overdue', action: `Flagged overdue allocation ${item.id}`, actor: 'System', time: item.expectedReturn, module: 'Allocations', detail: item.holder }))
  audits.forEach((cycle) => { cycle.items?.filter((item) => ['Missing', 'Damaged'].includes(item.result)).forEach((item) => add({ id: `audit-${cycle.id}-${item.assetTag}-${item.result}`, type: 'audit', title: 'Audit Discrepancy Flagged', message: `${item.assetName} (${item.assetTag}) was marked ${item.result} in ${cycle.name}.`, time: item.checkedOn || cycle.closedOn || cycle.createdOn, module: 'Audits', actor: item.checkedBy || cycle.auditors?.[0] || 'Auditor', priority: 'critical' }, { id: `log-audit-${cycle.id}-${item.assetTag}`, type: 'audit', action: `Marked ${item.assetTag} as ${item.result}`, actor: item.checkedBy || 'Auditor', time: item.checkedOn || cycle.createdOn, module: 'Audits', detail: cycle.name })) })
  registeredUsers.forEach((item) => logs.push({ id: `log-user-${item.employeeId}`, type: 'user', action: `Created employee account ${item.employeeId}`, actor: item.fullName, time: 'Account registration', module: 'Employees', detail: item.email }))

  if (!notifications.length) notifications.push(
    { id: 'sample-asset', type: 'asset', title: 'Asset Assigned', message: 'Dell Latitude 5440 (AF-0114) was assigned to Priya Sharma.', time: '10 minutes ago', module: 'Allocations', actor: 'Asset Manager', priority: 'normal' },
    { id: 'sample-maintenance', type: 'maintenance', title: 'Maintenance Approved', message: 'Maintenance request MR-0102 was approved and assigned to Vikram Singh.', time: '35 minutes ago', module: 'Maintenance', actor: 'Asset Manager', priority: 'attention' },
    { id: 'sample-booking', type: 'booking', title: 'Booking Reminder', message: 'Meeting Room B2 booking starts in 15 minutes.', time: '1 hour ago', module: 'Bookings', actor: 'System', priority: 'attention' },
    { id: 'sample-audit', type: 'audit', title: 'Audit Discrepancy Flagged', message: 'Asset AF-0042 was marked Missing in Q3 IT Asset Verification.', time: '2 hours ago', module: 'Audits', actor: 'Rahul Verma', priority: 'critical' },
  )
  if (!logs.length) notifications.forEach((item) => logs.push({ id: `log-${item.id}`, type: item.type, action: item.message, actor: item.actor, time: item.time, module: item.module, detail: item.title }))
  return { notifications: notifications.reverse(), logs: logs.reverse() }
}

export default function Notifications({ initialTab = 'notifications' }) {
  const { user } = useAuth()
  const feed = useMemo(() => buildFeed(), [])
  const [tab, setTab] = useState(initialTab)
  const [search, setSearch] = useState('')
  const [type, setType] = useState('All')
  const [showUnread, setShowUnread] = useState(false)
  const [readIds, setReadIds] = useState(() => readStore('assetflow_read_notifications'))
  const [selected, setSelected] = useState(null)
  const saveRead = (ids) => { setReadIds(ids); localStorage.setItem('assetflow_read_notifications', JSON.stringify(ids)) }
  const markRead = (id) => saveRead(readIds.includes(id) ? readIds : [...readIds, id])
  const markAll = () => saveRead(feed.notifications.map((item) => item.id))
  const unread = feed.notifications.filter((item) => !readIds.includes(item.id)).length
  const filteredNotifications = feed.notifications.filter((item) => (!showUnread || !readIds.includes(item.id)) && (type === 'All' || item.type === type) && [item.title, item.message, item.module, item.actor].some((value) => value.toLowerCase().includes(search.toLowerCase())))
  const filteredLogs = feed.logs.filter((item) => (type === 'All' || item.type === type) && [item.action, item.actor, item.module, item.detail].some((value) => String(value).toLowerCase().includes(search.toLowerCase())))

  return <div className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex items-center justify-between"><div><p className="text-sm font-medium text-[#7a6475]">Updates & traceability</p><h1 className="mt-1 text-2xl font-bold text-[#31232e]">Activity Logs & Notifications</h1><p className="mt-2 text-sm text-slate-600">Stay informed about workflow updates and review who performed every recorded action.</p></div><div className="rounded-lg bg-[#f7f3f6] px-4 py-3 text-right"><p className="text-xs text-slate-500">Viewing as</p><p className="text-sm font-semibold text-[#4f3448]">{user?.role?.replaceAll('_', ' ')}</p></div></div>
    <div className="grid grid-cols-4 gap-4">{[['Unread', unread, Bell], ['Critical Alerts', feed.notifications.filter((item) => item.priority === 'critical').length, ShieldAlert], ['Workflow Updates', feed.notifications.filter((item) => item.actor !== 'System').length, CheckCheck], ['Logged Actions', feed.logs.length, ClipboardCheck]].map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-[#e6dee4] bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-[#31232e]">{value}</p></div><div className="h-fit rounded-lg bg-[#f1eaf0] p-2.5 text-[#4f3448]"><Icon size={20}/></div></div></div>)}</div>
    <div className="grid grid-cols-2 gap-2 rounded-xl border border-[#e6dee4] bg-white p-2"><button className={`rounded-lg px-4 py-3 text-sm font-semibold ${tab === 'notifications' ? 'bg-[#4f3448] text-white' : 'text-slate-600'}`} onClick={() => setTab('notifications')}>Notifications {unread > 0 && <span className="ml-2 rounded-full bg-red-500 px-2 py-0.5 text-xs text-white">{unread}</span>}</button><button className={`rounded-lg px-4 py-3 text-sm font-semibold ${tab === 'activity' ? 'bg-[#4f3448] text-white' : 'text-slate-600'}`} onClick={() => setTab('activity')}>Full Activity Log</button></div>
    <section className="rounded-xl border border-[#e6dee4] bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-[#e6dee4] p-5"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="w-full rounded-lg border border-[#ddd3da] py-2.5 pl-10 pr-3 outline-none" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${tab === 'notifications' ? 'notifications' : 'activity logs'}...`}/></div><select className="rounded-lg border border-[#ddd3da] px-3 py-2.5 text-sm" value={type} onChange={(event) => setType(event.target.value)}><option>All</option><option value="asset">Assets</option><option value="maintenance">Maintenance</option><option value="booking">Bookings</option><option value="transfer">Transfers</option><option value="overdue">Overdue</option><option value="audit">Audits</option><option value="user">Users</option></select>{tab === 'notifications' && <><button className={`rounded-lg border px-3 py-2.5 text-sm ${showUnread ? 'border-[#4f3448] bg-[#f1eaf0] text-[#4f3448]' : 'border-[#ddd3da] text-slate-600'}`} onClick={() => setShowUnread(!showUnread)}>Unread only</button><button className="inline-flex items-center gap-2 rounded-lg bg-[#4f3448] px-3 py-2.5 text-sm font-medium text-white" onClick={markAll}><CheckCheck size={16}/>Mark all read</button></>}</div>
      {tab === 'notifications' ? <div className="divide-y divide-slate-100">{filteredNotifications.map((item) => { const Icon = iconMap[item.type] || Bell; const isRead = readIds.includes(item.id); return <button key={item.id} className={`flex w-full items-start gap-4 p-5 text-left hover:bg-[#fcfafb] ${isRead ? 'opacity-65' : ''}`} onClick={() => { markRead(item.id); setSelected(item) }}><div className={`rounded-lg p-2.5 ${colorMap[item.type]}`}><Icon size={19}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-semibold text-[#31232e]">{item.title}</p>{!isRead && <span className="h-2 w-2 rounded-full bg-[#4f3448]"/>}{item.priority === 'critical' && <span className="rounded-full bg-red-50 px-2 py-0.5 text-[10px] font-semibold uppercase text-red-700">Critical</span>}</div><p className="mt-1 text-sm text-slate-600">{item.message}</p><p className="mt-2 text-xs text-slate-400">{item.module} · {item.actor}</p></div><span className="whitespace-nowrap text-xs text-slate-500">{item.time}</span></button>})}</div> : <ActivityTable rows={filteredLogs}/>} 
    </section>
    {selected && <div className="fixed inset-0 z-20 grid place-items-center bg-black/30 p-6"><div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-[#7a6475]">{selected.module}</p><h2 className="mt-1 text-xl font-semibold text-[#31232e]">{selected.title}</h2></div><button onClick={() => setSelected(null)}><XCircle size={19}/></button></div><p className="mt-4 text-sm leading-6 text-slate-600">{selected.message}</p><div className="mt-5 grid grid-cols-2 gap-3 rounded-lg bg-[#f8f5f7] p-4 text-sm"><div><p className="text-xs text-slate-500">Triggered by</p><p className="font-medium">{selected.actor}</p></div><div><p className="text-xs text-slate-500">Time</p><p className="font-medium">{selected.time}</p></div></div></div></div>}
  </div>
}

function ActivityTable({ rows }) { return <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b bg-[#fcfafb] text-xs uppercase text-slate-500">{['Action', 'User / Actor', 'Time', 'Module', 'Details'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{rows.map((item) => { const Icon = iconMap[item.type] || Check; return <tr key={item.id} className="border-b border-slate-100"><td className="px-4 py-4"><span className="flex items-center gap-2 font-medium text-[#31232e]"><Icon className="text-[#4f3448]" size={16}/>{item.action}</span></td><td className="px-4 py-4 text-slate-600">{item.actor}</td><td className="px-4 py-4 text-slate-600">{item.time}</td><td className="px-4 py-4"><span className="rounded-full bg-[#f1eaf0] px-2.5 py-1 text-xs font-semibold text-[#4f3448]">{item.module}</span></td><td className="max-w-80 px-4 py-4 text-slate-500">{item.detail}</td></tr>})}</tbody></table></div> }
